# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-hello-world

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  memorySize: 128
  #environment:
  #  RedisHost: ${file(./redis.lab.yml):host}
  #  RedisPort: ${file(./redis.lab.yml):port}
  #vpc:
  #  securityGroupIds: [ "sg-5f599127" ]
  #  subnetIds: [ "subnet-54b9121d", "subnet-3c32905b", "subnet-32729c69" ]

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
  include:
    - ../handler/*js
    - ../requestLambda.js
    - ../redis.lab.js
    - node_modules/double-ended-queue/**
    - node_modules/redis/**
    - node_modules/redis-commands/**
    - node_modules/redis-parser/**
    - node_modules/uuid/**

functions:
  env:
    handler: handler.env
    events:
      - http:
          path: env
          method: get
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: helloWorld
          method: get
  id2LetterMap:
    handler: handler.id2LetterMap
    events:
      - http:
          path: id2LetterMap
          method: post
  letterReducer:
    handler: handler.letterReducer
    events:
      - http:
          path: letterReducer
          method: post
  toStringReducer:
    handler: handler.toStringReducer
    events:
      - http:
          path: toStringReducer
          method: post

