service: serverless-hello-world

provider:
  name: google
  runtime: nodejs
  project: vibrant-mantis-723
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/keyfile.json
  #region: eu-west-1
  memorySize: 128

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - package-lock.json
    - .gitignore
    - .git/**
  include:
    - ../handler/*js
    - ../requestLambda.js
    - ../redis.lab.js

functions:
  env:
    handler: env
    events:
      - http: path
  helloWorld:
    handler: helloWorld
    events:
      - http: path
  id2LetterMap:
    handler: id2LetterMap
    events:
      - http: path
  letterReducer:
    handler: letterReducer
    events:
      - http: path
  toStringReducer:
    handler: toStringReducer
    events:
      - http: path

